import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import LoadingScreen from "../components/LoadingScreen";
import PageTransitionProvider from "../components/PageTransitionProvider";
import Header from "../components/Header";
import NavigationEvents from "../components/NavigationEvents";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${notoSansJP.variable} antialiased`}
      >
        <LoadingScreen />
        <NavigationEvents />
        <Header />
        <PageTransitionProvider>
          {children}
        </PageTransitionProvider>
      </body>
    </html>
  );
}
